[project]
title = "Amazon Popular Books"
version = "0.1.0"
port = 8501
slug = "amazon-popular-books"  
entrypoint = "hello.py"    

[branding]
name = "Amazon Popular Books"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.amazon]
type = "csv"
path = "data/amazon.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"